blueprint:
  name: Media Player


  description: |
    # Philips Hue Tap Dial Switch 
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input: 
    media_player:
      name: Media Player
      description: Configure ZHA integration settings.
      icon: mdi:zigbee
      collapsed: true
      input:
        media_player_remote:
          name: Media Player (ZHA)
          description: |
            `optional` `device`

            Select the Philips Hue Tap Dial Switch device from ZHA. Leave empty if not using ZHA.
          default: {}
          selector:
            device:
              entity:
                - device_class:
                    - tv
              multiple: false  
    dial_custom:
      name: Dial - Custom Actions
      collapsed: true
      icon: mdi:rotate-3d-variant
      input:
        rotate_left:
          name: Rotate Left
          default: []
          selector:
            action: {}
        rotate_right:
          name: Rotate Right
          default: []
          selector:
            action: {}
    media_sources:
      name: Media Sources
      selector:
        select:
          options:
            - label: Jellyfin
              value: Jellyfin
            - label: Youtube
              value: Youtube
            - label: Twitch
              value: Twitch
          multiple: true
    gaming_sources:
      name: Gaming Sources
      selector:
        select:
          options:
            - label: PS5 Game Console
              value: PS5 Game Console
          multiple: true
    music_sources:
      name: Gaming Sources
      selector:
        select:
          options:
            - label: Spotify - Music and Podcasts
              value: Spotify - Music and Podcasts
          multiple: true
mode: single
max_exceeded: silent


variables:
  # Integration config
  media_player: !input media_player
  zha_command: "{{ trigger.event.data.command if trigger.event is defined else '' }}"
  command: >-
    {% if zha_command != '' %}
      {{ zha_command }}
    {% endif %}
  step_mode: >-
    {% if trigger.event is defined %}
      {{ trigger.event.data.params.step_mode | default('0') }}
    {% endif %}
  step_size: >-
    {% if trigger.event is defined %}
      {{ trigger.event.data.params.step_size | default(0) }}
    {% elif trigger.payload_json is defined %}
      {{ trigger.payload_json.action_step_size | default(0) }}
    {% else %}0
    {% endif %}
  is_rotation: "{{ command == 'step_with_on_off' }}"
  rotate_left: "{{ is_rotation and step_mode == 'StepMode.Down' and step_size | int(0) != 255 }}"
  rotate_right: "{{ is_rotation and step_mode == 'StepMode.Up' and step_size | int(0) != 255 }}"
triggers:
  - trigger: event
    event_type: zha_event
    event_data:
      device_id: !input media_player_remote
    id: zha_event
    
actions:
  - choose:
      # ========== DIAL ==========
      - conditions: "{{ rotate_left }}"
        sequence: !input rotate_left
      - conditions: "{{ rotate_right }}"
        sequence: !input rotate_right
