blueprint:
  name: Media Player


  description: |
    # Philips Hue Tap Dial Switch 
  domain: automation
  homeassistant:
    min_version: 2024.10.0
  input: 
    media_player:
      name: Media Player
      description: Configure ZHA integration settings.
      icon: mdi:zigbee
      collapsed: true
      input:
        media_player_remote:
          name: Media Player (ZHA) 1
          description: |
            `optional` `device`

            Select the Philips Hue Tap Dial Switch device from ZHA. Leave empty if not using ZHA.
          default: {}
          selector:
            entity:
              multiple: false
              filter:
                - device_class: tv
    media_sources:
      name: Media Sources
      selector:
        select:
          options:
            - label: Jellyfin
              value: Jellyfin
            - label: YouTube
              value: YouTube
            - label: Twitch
              value: Twitch
          multiple: true
    gaming_sources:
      name: Gaming Sources
      selector:
        select:
          options:
            - label: PS5 Game Console
              value: PS5 Game Console
          multiple: true
    music_sources:
      name: Gaming Sources
      selector:
        select:
          options:
            - label: Spotify - Music and Podcasts
              value: Spotify - Music and Podcasts
          multiple: true
    on_off:
      name: On/Off
      collapsed: true
      input:
        turn_on:
          name: Turn On
          default: []
          selector:
            action: {}
        turn_off:
          name: Turn Off
          default: []
          selector:
            action: {}     
    play_pause:
      name: Play/Pause
      collapsed: true
      input:
        play:
          name: Play
          default: []
          selector:
            action: {}
        pause:
          name: Pause
          default: []
          selector:
            action: {}
    source:
      name: Source
      collapsed: true
      input:
        media_source:
          name: Media
          default: []
          selector:
            action: {}
        gaming_source:
          name: Gaming
          default: []
          selector:
            action: {}
        music_source:
          name: Music
          default: []
          selector:
            action: {}
                      
mode: single
max_exceeded: silent


variables:
  # Integration config
   media_player_remote: !input media_player_remote
   event: "{{ trigger.id }}"


triggers:
  - trigger: state
    entity_id: !input media_player_remote
    id: turned_on
    to: "on"
  - trigger: state
    entity_id: !input media_player_remote
    id: turned_off
    to: "off"
    
  - trigger: state
    entity_id: !input media_player_remote
    id: payed
    to: "playing"
  - trigger: state
    entity_id: !input media_player_remote
    id: paused
    from: "playing"
    to: "paused"
    
  - trigger: state
    entity_id: !input media_player_remote
    attribute: source
    id: YouTube
    to: "YouTube"
  - trigger: state
    entity_id: !input media_player_remote
    attribute: source
    id: Jellyfin
    to: "Jellyfin"
  - trigger: state
    entity_id: !input media_player_remote
    attribute: source
    id: Twitch
    to: "Twitch"
  - trigger: state
    entity_id: !input media_player_remote
    attribute: source
    id: PS5 Game Console
    to: "PS5 Game Console"
  - trigger: state
    entity_id: !input media_player_remote
    attribute: source
    id: Spotify - Music and Podcasts
    to: "Spotify - Music and Podcasts"

    
actions:
  - choose:
      # ========== DIAL ==========
      - conditions: "{{ event in media_sources }}"
        sequence: !input media_source
